### ISSUE TITLE
Pushes going to pushwoosh but not device

### ISSUE THREAD

**Issue by devcheetah** [Pushwoosh/pushwoosh-parse-adapter#1]
`{ 
   "where": { 
     "deviceType": { 
       "$in": [ 
         "android" 
       ] 
     }
   }, 
   "data": { 
     "title": "Test", 
     "alert": "Parse Push"
   } 
 }`

This is sending the push to pushwoosh but its not actually sending the push to any device.  I can send to the device from the pushwoosh site as well as the pushwoosh remote API fine.

**Comment by FallDi** [comment]
Can you send notification without `where` condition and inform about results? Also please confirm that Parse Server contains devices in MongoDB. You can use https://github.com/ParsePlatform/parse-dashboard as fronted for Parse Server.

**Comment by devcheetah** [comment]
Yeah, I have the device in mongodb.  I have the dashboard that I can see the device in installations.  Same device info that went to pushwoosh.   Regardless if I use the push functions in dashboard or the parse push API, it doesn't send devices it looks like.   The device in installations shows android with all the device ids, etc.  So its definitely capturing everything about the device.

**Comment by FallDi** [comment]
Hm. To fully understand the issue, we need the application code from Pushwoosh. Please provide it here https://www.pushwoosh.com/contact-us/ and we check logs of API request for this application to reproduce and fix issue.

**Comment by devcheetah** [comment]
I put in a request on that form referencing this issue.

**Comment by FallDi** [comment]
Thanks. Now i found api createMessage request from you parseServer backend. 

```
{
  "request": {
    "application": "A1.....",
    "auth": "q5q......",
    "notifications": [
      {
        "send_date": "now",
        "devices": [
      "|ID|1|:eZS1fyfwqzA:APA91bFqkNc3mAZcxO6xsRPdTOiMEOJE1Tb4a9aRWFFw0w88Okyd2vPjieVf6mt6vG1QL56rAD3q2hAUb_48idfi-0f3d-aoSw28ZwYMutjPIMYIAc_PQp9UTHdnZzlDCv09CNK4SFec"
        ],
        "content": {
          "en": "Push remote api"
        }
      }
    ]
  }
}
```
pushtoken that at devices array contains wrong characters at start **|ID|1|:** i think it token stored such as MongoDB. And it some problem at database migration. If you remove from mongo device prefix then push will be delivered successfully.

**Comment by devcheetah** [comment]
Thanks, FallDi, that seems to have been the problem.  Heres the problem.  I used the parse android library and used the standard way of add the installation.  So I guess I need to figure out a way for it to not include that starting ID section to the string.

**Comment by FallDi** [comment]
It's great that we've found the cause! I would be happy to help again, have a nice day;)
