### ISSUE TITLE
"mutable-content" not possible to set

### ISSUE THREAD

**Issue by Mortenest** [Pushwoosh/pushwoosh-parse-adapter#2]
Hi, 

Can you please update the adapter to also contain the "mutable-content" flag inside the "aps" dictionary?

- Morten

**Comment by shaders** [comment]
Could you send pull-request?

**Comment by Mortenest** [comment]
https://github.com/Pushwoosh/pushwoosh-parse-adapter/pull/3

**Comment by shaders** [comment]
merged
