### ISSUE TITLE
Npmjs not updated and lib missing

### ISSUE THREAD

**Issue by Mortenest** [Pushwoosh/pushwoosh-parse-adapter#4]
Hi

Can you please update the npmjs version to "1.2.0"?

Furthermore, I tried installing the pushwoosh-parse-adapter directly with the github path ("pushwoosh-parse-adapter" : "Pushwoosh/pushwoosh-parse-adapter"), but when I do that, the whole lib folder is missing, which means that it installs fine, but won't compile as the actual scripts are missing.

best regards
Morten

**Comment by Mortenest** [comment]
bump

**Comment by wfhm** [comment]
@Mortenest npm version was updated to 1.2.0. Please let us know if the issue with missing lib folder is persistent with the latest one.

**Comment by Mortenest** [comment]
Hey @wfhm, it seems to be working, so everything is all jolly now :) thanks
